make show.sql in progress

diff --git a/bin/db/setup b/bin/db/setup
--- a/bin/db/setup
+++ b/bin/db/setup
@@ -1,5 +1,5 @@
 #! /usr/bin/bash
--e # stop if it fails at any point
+set -e # stop if it fails at any point
 
 CYAN='\033[1;36m'
 NO_COLOR='\033[0m'
@@ -7,12 +7,12 @@ LABEL="db-setup"
 printf "${CYAN}== ${LABEL}${NO_COLOR}\n"
 
 ABS_PATH=$(readlink -f "$0")
-BIN_PATH=$(dirname $ABS_PATH)
+DB_PATH=$(dirname $ABS_PATH)
 
-echo $BIN_PATH
+echo $DB_PATH
 
-source "$BIN_PATH/drop"
-source "$BIN_PATH/create"
-source "$BIN_PATH/schema-load"
-source "$BIN_PATH/db/seed"
-python "$BIN_PATH/db/update_cognito_user_ids"
+source "$DB_PATH/drop"
+source "$DB_PATH/create"
+source "$DB_PATH/schema-load"
+source "$DB_PATH/seed"
+python "$DB_PATH/update_cognito_user_ids"
